version: "3"
services:
    planme_backend:
        restart: always
        build:
            context: ./planme_backend
            dockerfile: Dockerfile
        volumes:
            - ./planme_backend:/app
        environment: 
            - NODE_ENV=development
            - PORT=5000
            - DB_USER=planme_user
            - DB_PASSWORD=PI3A8gLDftt5GKi7
            - DB_HOST=planme_postgres
            - DB_PORT=5432
            - DB_NAME=planme_db
        ports:
            - "5000:5000"
    nginx:
        restart: always
        depends_on:
            - planme_backend
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
    planme_postgres:
        image: "postgres:12"
        environment:
        - POSTGRES_USER=planme_user
        - POSTGRES_PASSWORD=PI3A8gLDftt5GKi7
        - POSTGRES_DB=planme_db
        volumes:
        - database-data:/var/lib/postgresql/data/
        - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
        ports:
        - "5432:5432"
volumes:
  database-data: