name: planme_flutter
description: Time Management Application

publish_to: "none" 

version: 1.0.0+1

environment:
    sdk: ">=2.8.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    provider: ^4.3.2+3
    dio: ^3.0.10
    shared_preferences: ^0.5.12+4
    circular_countdown_timer: ^0.0.8
    table_calendar: ^2.3.3
    intl: ^0.16.1
    fl_chart: ^0.12.2
    cupertino_icons: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    fonts:
        - family: Nunito
          fonts:
              - asset: assets/fonts/Nunito-Regular.ttf
              - asset: assets/fonts/Nunito-Bold.ttf
                weight: 700
              - asset: assets/fonts/Nunito-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Nunito-Light.ttf
                weight: 300
